name: Integrity Check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]

env:
  COSMOS_ENDPOINT: ${{ secrets.COSMOS_ENDPOINT }}
  COSMOS_KEY: ${{ secrets.COSMOS_KEY }}

jobs:

  audit:
    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Audit Packages
        run: pnpm audit --audit-level moderate

  test:
    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup NodeJS with PNPM Caching
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      
      - name: Install NodeJS Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint for Code-Style Errors
        run: pnpm lint

#      - name: Run Unit Tests
#        run: pnpm test

      - name: Run Build
        run: pnpm build
